import type { Lang } from "./cv-model";

export const ui = {
  ar: {
    appName: "استوديو السيرة",
    tagline: "أنشئ وعدّل سيرة ATS من اللينك مباشرة",
    cvTab: "المعاينة",
    atsTab: "اختبار ATS",
    editTab: "تحرير",
    language: "English",
    printPdf: "تحميل PDF",
    downloadTxt: "تحميل TXT",
    downloadDoc: "تحميل Word",
    copyText: "نسخ النص",
    copied: "تم نسخ النص",
    copyFail: "تعذر النسخ",
    scoreTitle: "نتيجة التوافق",
    originalTitle: "سيرة بعمودين",
    originalHint: "الملفات ذات العمودين وأشرطة المهارات تسجّل عادة حوالي 40. هذه النسخة عمود واحد ونص.",
    thisVersion: "هذه السيرة",
    gradeExcellent: "ممتاز — جاهزة للإرسال",
    gradeStrong: "قوي — تعديلات بسيطة",
    gradeFair: "متوسط — يحتاج تحسين",
    gradeWeak: "ضعيف — أعد الصياغة",
    checksTitle: "فحوصات التنسيق والمحتوى",
    keywordsTitle: "الكلمات المفتاحية",
    found: "موجود",
    missing: "غير موجود",
    jdTitle: "مطابقة إعلان الوظيفة",
    jdHint: "الصق الوصف الوظيفي أو اختر نموذجًا لاختبار الكلمات المطلوبة.",
    jdPlaceholder: "الصق إعلان الوظيفة هنا…",
    runMatch: "اختبار المطابقة",
    clearJd: "مسح",
    matchScore: "نسبة التطابق",
    matched: "موجود في السيرة",
    notMatched: "ناقص — أضفه إن كان ينطبق عليك",
    parserTitle: "كيف يقرأ النظام السيرة",
    parserHint: "هذا هو النص الخام الذي تفهرسه أنظمة ATS. لا جداول ولا صور.",
    howTitle: "لماذا هذا التنسيق ينجح مع ATS؟",
    howItems: [
      "عمود واحد حتى لا يختلط ترتيب الخبرات.",
      "المهارات مكتوبة كنص بدل أشرطة ملونة لا تُقرأ.",
      "التواريخ داخل سطر الوظيفة وليس في عمود جانبي.",
      "عناوين قياسية وكلمات المجال داخل النص.",
      "أرقام إنجاز واضحة متى توفرت.",
    ],
    samplesLabel: "نماذج للإعلانات",
    exportHint: "حمّل PDF نصيًا (A4 أو Letter). تجنّب رفع سكانر أو ملف بعمودين.",
    pass: "نجاح",
    warn: "تحسين",
    fail: "فشل",
    coverage: "التغطية",
    pdfTitle: "أفضل تنسيقات PDF للـ ATS",
    pdfSubtitle: "ملف نصي قابل للنسخ والبحث — ليس صورة. اختر الحجم حسب سوق الوظيفة.",
    pdfClose: "إغلاق",
    pdfDownloading: "جاري إنشاء الملف…",
    pdfDone: "تم التحميل",
    pdfError: "تعذر إنشاء الملف. حاول مرة أخرى.",
    pdfPrint: "طباعة من المتصفح",
    pdfRecommended: "موصى به",
    pdfA4Title: "ATS A4",
    pdfA4Body: "الحجم القياسي في مصر والخليج وأوروبا. نص قابل للنسخ، عمود واحد، خط مضمّن.",
    pdfA4Meta: "A4 · نص حقيقي · بدون حماية",
    pdfLetterTitle: "ATS US Letter",
    pdfLetterBody: "لبوابات أمريكا وكندا: Workday وGreenhouse وLinkedIn Easy Apply.",
    pdfLetterMeta: "Letter 8.5×11 · نص حقيقي · بدون حماية",
    pdfStrictTitle: "أقصى توافق",
    pdfStrictBody: "أسود بالكامل بدون خطوط زخرفية. لأقدم أنظمة التتبع التي تتعثر في الألوان.",
    pdfStrictMeta: "بدون زخرفة · خط قياسي للإنجليزية",
    pdfDownload: "تحميل",
    pdfWhyTitle: "لماذا هذا الـ PDF؟",
    pdfWhyItems: [
      "النص قابل للنسخ والبحث — ATS لا يقرأ PDF الصورة أو السكانر.",
      "عمود واحد بترتيب منطقي.",
      "A4 للسوق المحلي والأوروبي، وUS Letter للوظائف الأمريكية.",
      "بدون جداول أو أشرطة مهارات أو صورة شخصية أو كلمة مرور.",
    ],
    pdfPanelTitle: "تنسيقات PDF",
    pdfPanelHint: "اختر ملفًا حسب سوق الوظيفة. الثلاثة نصية وجاهزة للرفع.",
    newCv: "سيرة جديدة",
    sampleCv: "نموذج محاسب",
    duplicateCv: "نسخة",
    deleteCv: "حذف",
    saved: "يُحفظ تلقائيًا على هذا الجهاز",
    cvLang: "لغة السيرة",
    cvLangAr: "عربي",
    cvLangEn: "English",
    sectionProfile: "البيانات الأساسية",
    name: "الاسم",
    headline: "المسمى الوظيفي",
    location: "المدينة",
    phone: "الهاتف",
    email: "البريد",
    sectionSummary: "الملخص المهني",
    sectionExperience: "الخبرة العملية",
    addJob: "إضافة وظيفة",
    removeJob: "حذف الوظيفة",
    jobTitle: "المسمى",
    company: "الجهة",
    start: "من",
    end: "إلى",
    currentJob: "الوظيفة الحالية",
    bullets: "المهام والإنجازات — سطر لكل بند",
    addBullet: "بند",
    sectionEducation: "المؤهلات",
    addEducation: "إضافة مؤهل",
    degree: "المؤهل",
    school: "الجامعة / الجهة",
    year: "السنة",
    sectionSkills: "المهارات",
    addSkillGroup: "مجموعة مهارات",
    groupTitle: "عنوان المجموعة",
    skillItems: "المهارات — سطر لكل مهارة",
    sectionLanguages: "اللغات",
    addLanguage: "إضافة لغة",
    langName: "اللغة",
    langLevel: "المستوى",
    sectionTraining: "الدورات — سطر لكل دورة",
    sectionInterests: "الاهتمامات — سطر لكل بند",
    exportJson: "تصدير نسخة",
    importJson: "استيراد",
    pickCv: "السير المحفوظة",
    emptyPreview: "ابدأ من التحرير على اليمين. المعاينة تتحدث فور الكتابة.",
    tailorTitle: "تعديل السيرة حسب الوظيفة",
    tailorHint: "اكتب المسمى والصق الوصف، ثم اضغط التعديل. كل مرة تُبنى السيرة من النسخة الأصلية قبل أي تخصيص، حتى لا تتراكم الجمل. لا تُضاف خبرة غير مكتوبة عندك.",
    tailorRole: "المسمى الوظيفي المستهدف",
    tailorRolePh: "مثال: محاسب تكاليف",
    tailorJd: "الوصف الوظيفي المطلوب",
    tailorJdPh: "الصق متطلبات الإعلان هنا…",
    tailorApply: "عدّل السيرة لهذا الإعلان",
    tailorRestore: "ارجع للنسخة قبل التعديل",
    tailorMatched: "ظهر في سيرتك وأُبرز",
    tailorSkipped: "في الإعلان ولم يُضف لأنه غير مذكور عندك",
    tailorDone: "تم تعديل السيرة لهذا الإعلان.",
  },
  en: {
    appName: "Resume Studio",
    tagline: "Create and edit an ATS resume from the link",
    cvTab: "Preview",
    atsTab: "ATS test",
    editTab: "Edit",
    language: "العربية",
    printPdf: "Download PDF",
    downloadTxt: "Download TXT",
    downloadDoc: "Download Word",
    copyText: "Copy text",
    copied: "Text copied",
    copyFail: "Could not copy",
    scoreTitle: "Compatibility score",
    originalTitle: "Two-column file",
    originalHint: "Two-column files with skill bars often score around 40. This version is one column of real text.",
    thisVersion: "This resume",
    gradeExcellent: "Excellent — ready to submit",
    gradeStrong: "Strong — minor edits",
    gradeFair: "Fair — needs work",
    gradeWeak: "Weak — rewrite",
    checksTitle: "Format and content checks",
    keywordsTitle: "Keywords",
    found: "Found",
    missing: "Missing",
    jdTitle: "Job description match",
    jdHint: "Paste a job ad or pick a sample to test required keywords.",
    jdPlaceholder: "Paste the job description here…",
    runMatch: "Run match",
    clearJd: "Clear",
    matchScore: "Match rate",
    matched: "Present in the resume",
    notMatched: "Missing — add only if it is true",
    parserTitle: "How ATS reads this resume",
    parserHint: "This is the raw text parsers index. No tables, no images.",
    howTitle: "Why this layout works with ATS",
    howItems: [
      "Single column so experience order stays intact.",
      "Skills written as text instead of unread graphic bars.",
      "Dates sit on the job line, not in a side rail.",
      "Standard headings and field keywords in the body.",
      "Clear metrics whenever you have them.",
    ],
    samplesLabel: "Sample job ads",
    exportHint: "Download a text-based PDF (A4 or Letter). Avoid scans and two-column files.",
    pass: "Pass",
    warn: "Improve",
    fail: "Fail",
    coverage: "Coverage",
    pdfTitle: "Best ATS PDF formats",
    pdfSubtitle: "Selectable, searchable text — not an image. Pick the page size for the job market.",
    pdfClose: "Close",
    pdfDownloading: "Building the file…",
    pdfDone: "Downloaded",
    pdfError: "Could not build the file. Try again.",
    pdfPrint: "Print from browser",
    pdfRecommended: "Recommended",
    pdfA4Title: "ATS A4",
    pdfA4Body: "Standard size for Egypt, the Gulf, and Europe. Selectable text, one column, embedded font.",
    pdfA4Meta: "A4 · real text · unlocked",
    pdfLetterTitle: "ATS US Letter",
    pdfLetterBody: "For US and Canada boards: Workday, Greenhouse, LinkedIn Easy Apply.",
    pdfLetterMeta: "Letter 8.5×11 · real text · unlocked",
    pdfStrictTitle: "Maximum parse",
    pdfStrictBody: "All-black, no decorative rules. For older ATS tools that stumble on color.",
    pdfStrictMeta: "No chrome · standard font for English",
    pdfDownload: "Download",
    pdfWhyTitle: "Why this PDF?",
    pdfWhyItems: [
      "Text is selectable and searchable — ATS cannot read a scanned or image PDF.",
      "One column in logical order.",
      "A4 for local and European roles, US Letter for American postings.",
      "No tables, skill bars, photo, or password.",
    ],
    pdfPanelTitle: "PDF formats",
    pdfPanelHint: "Pick a file for the job market. All three are text-based and upload-ready.",
    newCv: "New resume",
    sampleCv: "Accountant sample",
    duplicateCv: "Duplicate",
    deleteCv: "Delete",
    saved: "Saves automatically on this device",
    cvLang: "Resume language",
    cvLangAr: "Arabic",
    cvLangEn: "English",
    sectionProfile: "Basics",
    name: "Name",
    headline: "Headline",
    location: "City",
    phone: "Phone",
    email: "Email",
    sectionSummary: "Professional summary",
    sectionExperience: "Experience",
    addJob: "Add role",
    removeJob: "Remove role",
    jobTitle: "Title",
    company: "Company",
    start: "From",
    end: "To",
    currentJob: "Current role",
    bullets: "Duties and results — one per line",
    addBullet: "Bullet",
    sectionEducation: "Education",
    addEducation: "Add education",
    degree: "Degree",
    school: "School",
    year: "Year",
    sectionSkills: "Skills",
    addSkillGroup: "Skill group",
    groupTitle: "Group title",
    skillItems: "Skills — one per line",
    sectionLanguages: "Languages",
    addLanguage: "Add language",
    langName: "Language",
    langLevel: "Level",
    sectionTraining: "Training — one per line",
    sectionInterests: "Interests — one per line",
    exportJson: "Export backup",
    importJson: "Import",
    pickCv: "Saved resumes",
    emptyPreview: "Start in the editor. The preview updates as you type.",
    tailorTitle: "Tailor the resume to a job",
    tailorHint: "Enter the title and paste the description, then tailor. Each run starts from the resume as it was before any tailoring, so wording does not stack. Experience you did not write is never added.",
    tailorRole: "Target job title",
    tailorRolePh: "Example: Cost accountant",
    tailorJd: "Required job description",
    tailorJdPh: "Paste the job requirements…",
    tailorApply: "Tailor resume to this job",
    tailorRestore: "Restore the version before tailoring",
    tailorMatched: "Already in your resume and highlighted",
    tailorSkipped: "In the job ad, not added because it is not in your resume",
    tailorDone: "Resume tailored to this job.",
  },
} as const;

export function t(lang: Lang) {
  return ui[lang];
}
